### ISSUE TITLE
ofDirectory crash

### ISSUE THREAD

**Issue by cerupcat** [elliotwoods/ofxAssets#1]
For some reason on on most of the ofDirectory calls, ofxAssets crashes. Have you seen this before due to bad memory access. Have you seen this before?

**Comment by elliotwoods** [comment]
Heya!
I haven't seen that on osx or Windows so far. Which platform are you on?

**Comment by elliotwoods** [comment]
my first guess is that something is happening before something is initialised (e.g. something is being called before ofApp::setup). But no idea right now.

Could I ask:
1. Your platform, oF version, ofxAssets version
2. The app code which is triggering the crash
3. A screenshot of the debugger when the exception is thrown
4. Any relevant local variables from the debugger (e.g. is something uninitialized)

Thank you!

**Comment by elliotwoods** [comment]
i've rewritten ofxAssets a couple of times since may. maybe new version doesn't have the crash?

**Comment by rumitdesai** [comment]
Heyy !!
Do we need Boost library for ofxassets ?

**Comment by elliotwoods** [comment]
going to close this because we don't use ofDirectory any more in 0.9.0 version

@rumitdesai - the new version of openFrameworks moves to using std / boost filesystem functions, and comes with portions of boost which provides this.
ofxAssets now relies on the boost functions available in oF 0.9.0

If you need a version of ofxAssets which doesn't use the boost filesystem functions (i.e. for oF 0.8.4 and before) then please check https://github.com/elliotwoods/ofxAssets/tree/0.8.4

**Comment by rumitdesai** [comment]
Thank You @elliotwoods for your help, i appreciate.
